### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by scaytrase** [php-rpc/cruds#2]
- [x] [Bug] config is ignored on determining, which methods should be configured #3 
- [x] [Bug] Serialization\Deserialization groups are ignored #4
- [x] [Feature] Try to use Jms\Sf serializer as `EntityProcessor` #5
- [x] [Feature] Allow easy replacement\configuration of serializing event #6
- [x] [Improvement] Use `get` as readAction path as default #7
- [x] [Improvement] Allow multiple api mounts (usefull for path-based authorization) #8
- [x] [Improvement] Use entity as whole `criteria` when no criteria configurators used  (or single is explicitly set as string) #9
- [x] [Testing] Improve tests for bare-controller calls #10
- [x] [Testing] Improve tests for adapters #11
- [x] [Testing] Use different Kernels as separate test-suite #12
- [x] [Documentation] Improve documentation #13

**Comment by scaytrase** [comment]
All set, preparing for release
